version: "3.9"

services:
  backend:
    build: ./backend
    container_name: rico_backend
    ports:
      - "8000:8000"
    env_file:
      - .env.local
    volumes:
      - ./data:/app/data
    networks:
      - rico_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    profiles:
      - default

  n8n:
    image: n8nio/n8n:1.64.0
    container_name: rico_n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_EDITOR_BASE_URL=http://localhost:5678
      - N8N_GENERIC_TIMEZONE=Europe/Berlin
      - N8N_USER_MANAGEMENT_DISABLED=true
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_VERSION_NOTIFICATIONS_ENABLED=false
      - N8N_TEMPLATES_ENABLED=false
      - N8N_PERSONALIZATION_ENABLED=false
      - N8N_ONBOARDING_FLOW_DISABLED=true
    volumes:
      - ./n8n_data:/home/node/.n8n
    networks:
      - rico_net
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:5678/"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 60s
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: rico_nginx
    ports:
      - "80:80"
    volumes:
      - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - rico_net
    depends_on:
      backend:
        condition: service_healthy
      n8n:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

networks:
  rico_net:
    driver: bridge
