name: CI Verify (No Secrets Leaked)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      PPLX_API_KEY: ${{ secrets.PPLX_API_KEY }}
      OPENAI_MODEL: gpt-4o-mini
      CLAUDE_MODEL: claude-3-5-sonnet-20240620
      PPLX_MODEL: sonar-medium-online
      LLM_TIMEOUT_SECONDS: 35
      LLM_RETRIES: 1
      ENV_SOURCE: github-actions
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true

      - name: Static checks
        run: |
          echo "Checking that no .env.local exists in repo..."
          test ! -f .env.local
          echo "OK"

      - name: Print key status (no secrets)
        run: |
          python - <<'PY'
          import os
          def st(n): return "OK" if os.getenv(n) else "MISSING"
          print({"openai": st("OPENAI_API_KEY"), "claude": st("ANTHROPIC_API_KEY"), "perplexity": st("PPLX_API_KEY"), "env_source": os.getenv("ENV_SOURCE")})
          PY
