name: Deploy Rico System

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install Frontend Dependencies
      run: |
        cd frontend
        npm ci
    
    - name: Lint Frontend
      run: |
        cd frontend
        npm run lint || true

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Backend
      run: |
        cd backend
        docker build -t rico-backend:latest .
    
    - name: Build Frontend
      run: |
        cd frontend
        docker build -t rico-frontend:latest .
    
    - name: Test Docker Compose
      run: |
        docker-compose config

  deploy:
    runs-on: ubuntu-latest
    needs: [lint, build]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to Server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT || 22 }}
        script: |
          cd /opt/rico4
          git pull origin main
          bash deploy/deploy.sh
    
    - name: Health Check
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT || 22 }}
        script: |
          # Wait for services to be ready
          sleep 60
          
          # Check backend
          curl -f http://localhost:8000/health || exit 1
          echo "✅ Backend is healthy"
          
          # Check frontend
          curl -f http://localhost:3000/api/health || exit 1
          echo "✅ Frontend is healthy"
          
          # Check nginx
          curl -f http://localhost/health || exit 1
          echo "✅ Nginx is healthy"
          
          echo "🎉 All services are healthy!"