name: Rico System Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install -r backend/requirements.txt
        pip install pytest pytest-asyncio pytest-cov httpx
    
    - name: Block external APIs (Security)
      run: |
        echo "127.0.0.1 api.openai.com" | sudo tee -a /etc/hosts
        echo "127.0.0.1 api.anthropic.com" | sudo tee -a /etc/hosts
        echo "127.0.0.1 api.perplexity.ai" | sudo tee -a /etc/hosts
    
    - name: Run tests with coverage
      run: |
        cd backend
        pytest tests/ -v --cov=providers --cov=orchestrator --cov=api --cov=utils --cov-report=xml
      env:
        OPENAI_API_KEY: "test-key-openai"
        ANTHROPIC_API_KEY: "test-key-anthropic"
        PERPLEXITY_API_KEY: "test-key-perplexity"
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./backend/coverage.xml
        flags: backend
        name: backend-coverage

  frontend-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
        
    - name: Install dependencies
      run: |
        cd frontend
        npm ci
        
    - name: Run type check
      run: |
        cd frontend
        npm run type-check
        
    - name: Run lint
      run: |
        cd frontend
        npm run lint
        
    - name: Build application
      run: |
        cd frontend
        npm run build
      env:
        NEXT_PUBLIC_API_URL: "http://localhost:8000"

  integration-test:
    runs-on: ubuntu-latest
    needs: [test, frontend-test]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
        
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install backend dependencies
      run: |
        pip install -r backend/requirements.txt
        
    - name: Install frontend dependencies
      run: |
        cd frontend
        npm ci
        
    - name: Start backend server
      run: |
        cd backend
        uvicorn main:app --host 0.0.0.0 --port 8000 &
        sleep 10
      env:
        OPENAI_API_KEY: "test-key-openai"
        ANTHROPIC_API_KEY: "test-key-anthropic"
        PERPLEXITY_API_KEY: "test-key-perplexity"
        
    - name: Start frontend server
      run: |
        cd frontend
        npm run build
        npm start &
        sleep 10
      env:
        NEXT_PUBLIC_API_URL: "http://localhost:8000"
        
    - name: Test API endpoints
      run: |
        curl -f http://localhost:8000/health/quick || exit 1
        curl -f http://localhost:8000/ || exit 1
        curl -f http://localhost:8000/info || exit 1
        
    - name: Test frontend build
      run: |
        curl -f http://localhost:3000 || exit 1
